import baseEditEmp from "../../support/pageObject/baseEditEmployee.cy"

describe('M-012: Modul PIM - Edit Employee', () => {
  const BaseEditEmp = new baseEditEmp()

  it('M-012.001: Edit semua data personal', () => {
    cy.login ()
    BaseEditEmp.AksesmenuPIM()
    BaseEditEmp.editEmp()
    BaseEditEmp.menuPersonal()
    BaseEditEmp.clearNamaDepan()
    BaseEditEmp.editNamaDepan()
    BaseEditEmp.clearNamaTengah()
    BaseEditEmp.editNamaTengah()
    BaseEditEmp.clearNamaBelakang()
    BaseEditEmp.editNamaBelakang()
    BaseEditEmp.clearNamaPanggilan()
    BaseEditEmp.namaPanggilan()
    BaseEditEmp.clearID()
    BaseEditEmp.idPegawai()
    BaseEditEmp.simpanData()
  })

  it('M-012.008: Kosongkan semua data',()=>{
    cy.login ()
    BaseEditEmp.AksesmenuPIM()
    BaseEditEmp.editEmp()
    BaseEditEmp.menuPersonal()
    BaseEditEmp.clearNamaDepan()
    BaseEditEmp.clearNamaBelakang()
    BaseEditEmp.simpanData()
  })

  it('M-012.009: Batal ubah', () => {
    cy.login ()
    BaseEditEmp.AksesmenuPIM()
    BaseEditEmp.editEmp()
    BaseEditEmp.menuPersonal()
    BaseEditEmp.clearNamaDepan()
    BaseEditEmp.editNamaDepan()
    BaseEditEmp.clearNamaTengah()
    BaseEditEmp.editNamaTengah()
    BaseEditEmp.clearNamaBelakang()
    BaseEditEmp.editNamaBelakang()
    BaseEditEmp.clearNamaPanggilan()
    BaseEditEmp.namaPanggilan()
    BaseEditEmp.clearID()
    BaseEditEmp.idPegawai()
    BaseEditEmp.MenuLain()
  })

  it('M-012.005, M-012.006, M-012.007 : Karaketer lebih dari seharusnya', () => {
    cy.login ()
    BaseEditEmp.AksesmenuPIM()
    BaseEditEmp.editEmp()
    BaseEditEmp.menuPersonal()
    BaseEditEmp.clearNamaDepan()
    BaseEditEmp.editNamaDepan()
    BaseEditEmp.clearNamaTengah()
    BaseEditEmp.editNamaTengah()
    BaseEditEmp.clearNamaBelakang()
    BaseEditEmp.editNamaBelakang()
    BaseEditEmp.clearNamaPanggilan()
    BaseEditEmp.namaPanggilan()
    BaseEditEmp.clearID()
    BaseEditEmp.idPegawai()
    BaseEditEmp.OtherId()
    BaseEditEmp.DriverLicense()
    BaseEditEmp.simpanData()
  })

})